### ISSUE TITLE
simpler API for setupState

### ISSUE THREAD

**Issue by felixmariotto** [felixmariotto/three-mesh-ui#217]
Hi, I'd like to have opinions about a possible API change. Currently we have : 

```js
component.setupState( {
   state: 'name-of-the-state',
   attributes: {
      attribute: value
   }
} );
```

That's quite verbose for no reason, we could change to this : 

```js
component.setupState( 'name-of-the-state',  {
   attribute: value
} );
```

The update in the codebase is trivial, but of course it's not retrocompatible so users upgrading three-mesh-ui would have to update their codebase. At minimum we should throw a rich error if the first argument is an object, telling that the API changed with version x.x.x

**Comment by swingingtom** [comment]
Hey @felixmariotto that would indeed be less verbose +1

#### side note:
About the current implementation, currently the `.setState("stateName")` switches between states. 
On interactive elements, this would cause some issues like : 

A **disabled**_(state)_ element can be **hovered** _(state)_ and should therefore display **disabled**+**hovered**
A **selected**_(state)_ element can be **hovered** _(state)_ and should therefore display **selected**+**hovered**

Im not that far from this point in the 7.x.x branch

**Comment by felixmariotto** [comment]
Ah you mean that states could be cumulative, like CSS classes ? That would be nice indeed.

**Comment by swingingtom** [comment]
I know I talk (write) a lot about 7.x.x and I planned to propose something limited on 7 july... 

> Ah you mean that states could be cumulative, like CSS classes ? That would be nice indeed.

In a limited area of effect, but that's what I meant. I had a prototype on 7.x.x that made me believe this is reachable

**Comment by felixmariotto** [comment]
No worries for schedule man ! It's not like I've been very active here these past few months, I've had so much work... I will try to delegate more of it from next month, so I hope to have more free time soon. In the meantime I totally trust you, you have done an amazing job at managing the repo !

**Comment by JoeCoppola-HIA** [comment]
We've been pretty swamped over here this summer, but we are still very actively using Three Mesh UI. We look forward to 7.x.x, but are very content with its current version too, so no sweat at all. @swingingtom has indeed done a great job managing it, I follow a lot of the changes daily.

As for the cumulative states, how would it handle two states that change the same attribute, such as color? The latest state to be active would override the first active state?

**Comment by swingingtom** [comment]
@JoeCoppola-HIA thanks !

> As for the cumulative states, how would it handle two states that change the same attribute, such as color? The latest state to be active would override the first active state?

As it would be based on css, it should follow the same rules. 
1- First level order : CSS Specificity
2- Second level order : Line # ( from top to bottom )

The first case might be the simpler to explain : using CSS (file or string)
_* It worth noting that css files and or strings are mostly handleld browser side_
```css
/* This first sample shows 3 css queries with the same specifity */
/* As they share the same specificity, second level order will apply  */
/* Please note that this sample follows "LOVE/HATE order" which allows cumulation to play nice */
/* @see https://css-tricks.com/snippets/css/link-pseudo-classes-in-order/ */
button:hover{ /* when mouse hover */
    color : blue;
}
button:active{ /* when mouse down */
    color : yellow;
}
button:selected{ /* let's say its a switch button */
    color : red;
}
```
**Results :** 
**:hover**+**:active** will be yellow
**:hover**+**:selected** will be red

### We want :hover to override :active and/or :selected ?
#### Option 1- Place :hover after :active
```css
button:active{ color : yellow; }
button:selected{ color : red; }
button:hover{ color : blue; } /* now after other rules, takes priority over same specificity */
```
**Results :** 
**:hover**+**:active** will be blue
**:hover**+**:selected** will be blue

#### Option 2- Increase :hover specificity
```css
:root button:hover{ color : blue; }
button:active{ color : yellow; }
button:selected{ color : red; }
```
The order hasn't change, but the specificity of :hover is bigger than :active or :selected

**Results :** 
**:hover**+**:active** will be blue
**:hover**+**:selected** will be blue

#### Option 3- Add one rule for the cumulation
```css
button:hover{ color : blue; }
button:selected:hover{ color: blue; } /* new rule with bigger specificity */
button:active{ color : yellow; }
button:selected{ color : red; }
```
**Results :** 
**:hover**+**:active** will be yellow
**:hover**+**:selected** will be blue

Where it goes tricky is when defining from Object side. 
Objects would be great ....
```javascript
const styles = {
    ":hover": { color : 'blue'; }
    ":active": { color : 'yellow'; }
    ":selected": { color : 'red'; }
 }
const button = new ThreeMeshUI.Button( {textContent: "click me"} , styles );
```
The issue here is that object doesn't order keys, we could then not guarantee that :selected would be registered after :hover. We would go with less syntaxic friendly array or string
```javascript
const styles = [
    {":hover": { color : 'blue'; } }
    {":active": { color : 'yellow'; } }
    {":selected": { color : 'red'; } }
 ]
const button = new ThreeMeshUI.Button( {textContent: "click me"} , styles );
```
or 
```javascript
const styles = `
    :hover: { color : blue; }
    :active: { color : yellow; }
    :selected: { color : red; }
`
const button = new ThreeMeshUI.Button( {textContent: "click me"} , styles );
```
The advantage of the string, is that upgrading project code from js to css file would be easy. The same apply from css to js file

I will try to provide a POC asap.
